### ISSUE TITLE
OSE System Setup

### ISSUE THREAD

**Issue by ishuverma** [sabre1041/iot-ocp#1]
I needed to do the following in order to build the sensor:

Register the system, Add subscription, install Maven, JDK 1.8:

$ sudo subscription-manager register --username=rhnuser --password=rhnpasswd
$ sudo subscription-manager list --available  Find pool ID for RHEL subscription
$ sudo subscription-manager attach --pool=pool_id

$ sudo yum --enablerepo=rhel-7-server-optional-rpms install maven

$ yum install java-1.8.0-openjdk-devel

**Comment by sabre1041** [comment]
@ishuverma is this still an issue or can it be closed?
