### ISSUE TITLE
fis-app build error

### ISSUE THREAD

**Issue by danieloh30** [sabre1041/iot-ocp#22]
I got below error during fis-app build on cdk2.3 and still reproduce it.

=========================================================
Deploying FIS Application...

service "fis-app" created
imagestream "fis-app" created
buildconfig "fis-app" created
deploymentconfig "fis-app" created

Waiting for a running build..

Error from server: builds "fis-app-1" not found
Pulling image "registry.access.redhat.com/jboss-fuse-6/fis-karaf-openshift@sha256:48e7f7854878becec1a450e40da63b0a27da76ad63068b407ef03f3ac01cd0d1" ...
Pulling image "registry.access.redhat.com/jboss-fuse-6/fis-karaf-openshift@sha256:48e7f7854878becec1a450e40da63b0a27da76ad63068b407ef03f3ac01cd0d1" ...
Cloning "https://github.com/sabre1041/iot-ose.git" ...
	Commit:	41998b9336ac731fd4acf556526d450087ee4f6f (Merge pull request #19 from jawnsy/topics/license)
	Author:	Andrew Block <andy.block@gmail.com>
	Date:	Fri Dec 23 18:57:07 2016 -0500

==================================================================
Starting S2I Karaf Build .....
Maven build detected
Using custom maven settings from /tmp/src/configuration/settings.xml
Found pom.xml ...
Running 'mvn -Dmaven.repo.local=/tmp/artifacts/m2 -s /tmp/src/configuration/settings.xml clean install -DskipTests '
Picked up JAVA_TOOL_OPTIONS: -Duser.home=/home/jboss -Duser.name=jboss
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-29T02:52:58-04:00)
Maven home: /usr/share/java/maven-3
Java version: 1.8.0_111, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.111-1.b15.el7_2.x86_64/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.10.0-514.el7.x86_64", arch: "amd64", family: "unix"
Picked up JAVA_TOOL_OPTIONS: -Duser.home=/home/jboss -Duser.name=jboss
[INFO] Scanning for projects...
Downloading: https://repo.fusesource.com/nexus/content/groups/public/org/apache/karaf/tooling/karaf-maven-plugin/4.0.2.redhat-621079/karaf-maven-plugin-4.0.2.redhat-621079.pom
Downloading: https://repo.fusesource.com/nexus/content/groups/ea/org/apache/karaf/tooling/karaf-maven-plugin/4.0.2.redhat-621079/karaf-maven-plugin-4.0.2.redhat-621079.pom
Downloading: https://maven.repository.redhat.com/ga/org/apache/karaf/tooling/karaf-maven-plugin/4.0.2.redhat-621079/karaf-maven-plugin-4.0.2.redhat-621079.pom
Downloading: https://repo.maven.apache.org/maven2/org/apache/karaf/tooling/karaf-maven-plugin/4.0.2.redhat-621079/karaf-maven-plugin-4.0.2.redhat-621079.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin org.apache.karaf.tooling:karaf-maven-plugin:4.0.2.redhat-621079 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.karaf.tooling:karaf-maven-plugin:jar:4.0.2.redhat-621079 @
[ERROR] Unknown packaging: bundle @ line 6, column 14
@
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.redhat.examples.iot:iot-ose-routing-service:0.0.1-SNAPSHOT (/tmp/src/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin org.apache.karaf.tooling:karaf-maven-plugin:4.0.2.redhat-621079 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.karaf.tooling:karaf-maven-plugin:jar:4.0.2.redhat-621079: Could not transfer artifact org.apache.karaf.tooling:karaf-maven-plugin:pom:4.0.2.redhat-621079 from/to fusesource.m2 (https://repo.fusesource.com/nexus/content/groups/public): Remote host closed connection during handshake: SSL peer shut down incorrectly -> [Help 2]
[ERROR]     Unknown packaging: bundle @ line 6, column 14
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException
Aborting due to error code 1 from mvn command

error: build error: non-zero (13) exit code from registry.access.redhat.com/jboss-fuse-6/fis-karaf-openshift@sha256:48e7f7854878becec1a450e40da63b0a27da76ad63068b407ef03f3ac01cd0d1

fis-app build did not complete successfully. Status is: Failed

**Comment by sabre1041** [comment]
@danieloh30 this looks like there might have been either network or repository issues. Would you be able to try provisioning again?

Also, new support is available to restart at various points in the installation process

**Comment by danieloh30** [comment]
@sabre1041 It's working once I deleted project all, pulled this repo again and started over. It was probably network problem and now there is no issue any longer.
