### ISSUE TITLE
Build fails for rhel-zeppelin at the End

### ISSUE THREAD

**Issue by arashkaffamanesh** [sabre1041/iot-ocp#24]
Hello,

Thx for the great hard work, the build fails on OpenShift Origin, does this work only with OpenShift Enterprise?

In the logs I can see:

> This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register. There are no enabled repos.

[root@master iot-ocp]# ./init.sh --restart-from build-zeppelin
Restarting at Step "build-zeppelin"
No resources found
No resources found

Deploying Visualization Tool...

Error from server: services "rhel-zeppelin" already exists
Error from server: routes "rhel-zeppelin" already exists
Error from server: imagestreams "rhel-zeppelin" already exists
Error from server: persistentvolumeclaims "rhel-zeppelin" already exists
Error from server: buildconfigs "rhel-zeppelin" already exists
Error from server: deploymentconfigs "rhel-zeppelin" already exists

Waiting for a running build..

Build has failed

Provisioning Failed. Execute "./init.sh --restart-from build-zeppelin" to Restart From The Failed Stage

**Comment by sabre1041** [comment]
@arashkaffamanesh I have made a correction to the error rerunning the build. 

However, since the visualization tool is being built in a RHEL based image, the build must occur on a machine running RHEL. is your node running RHEL?

**Comment by arashkaffamanesh** [comment]
@sabre1041 
no, Origin is running on CentOS 7.3

**Comment by sabre1041** [comment]
@arashkaffamanesh Unfortunately, the project is configured to only utilize RHEL as a base.

As a temporary workaround, you could fork the project and swap out the imagestream RHEL->centos. The rest of the build should still continue to work. 

If you would like, please add an issue to support deployment of either RHEL or CentOS

**Comment by sabre1041** [comment]
Resolved in #26
